module:
  address: 0
  admin_toolbar: 0
  automated_cron: 0
  block: 0
  block_class: 0
  breakpoint: 0
  calendar: 0
  calendar_datetime: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  config_direct_save: 0
  contact: 0
  contextual: 0
  courier: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_entity_reference: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity: 0
  entity_browser: 0
  entity_embed: 0
  field: 0
  field_ui: 0
  file: 0
  file_browser: 0
  filter: 0
  geofield: 0
  geofield_map: 0
  help: 0
  history: 0
  image: 0
  imce: 0
  kint: 0
  leaflet: 0
  leaflet_views: 0
  link: 0
  masc_custom_blocks: 0
  masquerade: 0
  media_entity: 0
  media_entity_image: 0
  menu_block: 0
  menu_item_extras: 0
  menu_trail_by_path: 0
  menu_ui: 0
  metatag: 0
  metatag_app_links: 0
  modules_weight: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  permissions_by_term: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  redirect_404: 0
  redirect_domain: 0
  responsive_image: 0
  rng: 0
  rng_contact: 0
  rng_quick: 0
  rng_views: 0
  search: 0
  shortcut: 0
  simple_block: 0
  svg_image: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  unlimited_number: 0
  update: 0
  user: 0
  veoa: 0
  views_advanced_routing: 0
  views_bulk_edit: 0
  views_bulk_operations: 0
  views_templates: 0
  views_ui: 0
  menu_link_content: 1
  menu_parent_image: 1
  pathauto: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  neato: 0
  masc: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
