<?php

/**
 * @file
 * Contains migrate_masc_users.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function migrate_masc_users_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the migrate_masc_users module.
    case 'help.page.migrate_masc_users':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migrate masc users from csv file') . '</p>';
      return $output;

    default:
  }
}
